In [1]:
import tensorflow as tf

In [17]:
# import numpy as np
# data=np.arange(10)
# dataset=tf.data.Dataset.from_tensor_slices(data)

dataset=tf.data.Dataset.range(10)

for val in dataset:
  print(val.numpy())  #creates a dataset with numpy values and prints the numpy values from tensor slices

0
1
2
3
4
5
6
7
8
9


In [18]:
dataset=dataset.window(size=5,shift=1)

for window_val in dataset:
  print(window_val) #returns the iterables

<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>
<_VariantDataset element_spec=TensorSpec(shape=(), dtype=tf.int64, name=None)>


In [19]:
for window_val in dataset:
  print([item.numpy() for item in window_val])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


In [22]:
#or you can check out window elements in this way too
for window_val in dataset:
  for item in window_val:
    print(item.numpy(),end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [23]:
#let's get evenly sized elements

dataset=tf.data.Dataset.range(10)

dataset=dataset.window(size=5,shift=1,drop_remainder=True)
for val in dataset:
  print([item.numpy() for item in val])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


In [30]:
dataset = tf.data.Dataset.range(10)

# Window the data but only take those with the specified size
dataset = dataset.window(5, shift=1, drop_remainder=True)


# Flatten the windows by putting its elements in a single batch
dataset=dataset.flat_map(lambda window: window.batch(5))

for val in dataset:
  print(val.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [31]:
dataset=dataset.map(lambda window: (window[:-1], window[-1]) )

for features,labels in dataset:
  print("features= ",features.numpy())
  print("labels= ",labels.numpy())
  print()

features=  [0 1 2 3]
labels=  4

features=  [1 2 3 4]
labels=  5

features=  [2 3 4 5]
labels=  6

features=  [3 4 5 6]
labels=  7

features=  [4 5 6 7]
labels=  8

features=  [5 6 7 8]
labels=  9



In [32]:
#its is a good practise to shuffle the data

dataset=tf.data.Dataset.range(10)
dataset=dataset.window(size=5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window: window.batch(5))

dataset=dataset.map(lambda window: (window[:-1], window[-1]))
dataset=dataset.shuffle(buffer_size=10)

for features,labels in dataset:
  print("features= ",features.numpy())
  print("labels= ",labels.numpy())
  print()

features=  [3 4 5 6]
labels=  7

features=  [4 5 6 7]
labels=  8

features=  [1 2 3 4]
labels=  5

features=  [0 1 2 3]
labels=  4

features=  [5 6 7 8]
labels=  9

features=  [2 3 4 5]
labels=  6



In [33]:
# Create batches of windows
dataset=dataset.batch(2).prefetch(1)
for features,labels in dataset:
  print("features= ",features.numpy())
  print("labels= ",labels.numpy())
  print()

features=  [[1 2 3 4]
 [3 4 5 6]]
labels=  [5 7]

features=  [[4 5 6 7]
 [2 3 4 5]]
labels=  [8 6]

features=  [[0 1 2 3]
 [5 6 7 8]]
labels=  [4 9]

